version: '3'
services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: real_estate_crawler
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
volumes:
  data: